language: php
sudo: false

php:
  - 7.2
  - 7.3
  - 7.4

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

install:
  - composer install

before_script:

script:
  - ./vendor/bin/phpunit --coverage-clover=coverage.clover
